### ISSUE TITLE
Scroll jacking breaks scrolling on touch devices

### ISSUE THREAD

**Issue by ezekg** [andrewmarkle/andrewmarkle.github.io#1]
Hey, just an FYI, I was trying to read your article on multi tenancy in Rails, but scrolling on my iPad and iPhone is broken because of all the scroll-jacking going on. Might want to disable that, as it's quite frustrating not being able to scroll. 👌

**Comment by andrewmarkle** [comment]
You're right! That is very annoying!

Thanks so much for pointing that out. Should be fixed now.
